"""
F-11 端到端测试：完整验证Executor存储 -> Analyzer提取链路
"""
import asyncio
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "app"))

from app.agent.nodes.executor_node import executor_node
from app.agent.nodes.analyzer_node import analyzer_node
from app.agent.state import AgentState
from app.models.permission import PermissionContext


async def test_e2e_stock_query():
    """端到端测试：股票查询从Executor到Analyzer"""
    print("\n=== E2E Test: Stock Query ===")

    # 初始状态
    state = AgentState(
        query="查询IBM股票最近的交易数据",
        plan=[
            {
                "step": 1,
                "tool": "api_fetch",
                "api_id": "alpha_vantage_stock",
                "params": {
                    "endpoint": "获取日线数据",
                    "params": {"symbol": "IBM", "function": "TIME_SERIES_DAILY"}
                },
                "description": "获取IBM股票数据"
            }
        ],
        current_step=0,
        data_context={},
        messages=[]
    )

    permission = PermissionContext(user_id="1", role="employee")

    # Step 1: Executor执行
    print("\n[Step 1] Executor execution...")
    state = await executor_node(state, permission)

    # 验证Executor输出
    data_context = state.get("data_context", {})
    print(f"Data context keys: {list(data_context.keys())}")

    expected_key = "step_0_alpha_vantage_stock"
    if expected_key not in data_context:
        print(f"[FAIL] Expected key not found: {expected_key}")
        return

    value = data_context[expected_key]
    print(f"[PASS] Key format correct: {expected_key}")
    print(f"Value has 'success': {value.get('success')}")
    print(f"Value has 'data': {'data' in value}")
    print(f"Value has 'metadata': {'metadata' in value}")

    if value.get("success") and value.get("data"):
        data = value["data"]
        if isinstance(data, dict) and "rows" in data:
            print(f"[PASS] Data contains 'rows' field with {data.get('row_count', 0)} rows")
        else:
            print(f"[FAIL] Data missing 'rows' field")
            return
    else:
        print(f"[FAIL] Execution failed or no data")
        return

    # Step 2: Analyzer分析
    print("\n[Step 2] Analyzer extraction...")
    state = await analyzer_node(state)

    # 验证Analyzer输出
    messages = state.get("messages", [])
    if messages:
        last_message = messages[-1]
        print(f"[PASS] Analyzer generated message")
        print(f"Message type: {last_message.get('type')}")
        print(f"Message content length: {len(last_message.get('content', ''))}")
        print(f"Message preview: {last_message.get('content', '')[:200]}...")
    else:
        print(f"[FAIL] No message generated by Analyzer")


async def test_e2e_order_query():
    """端到端测试：订单查询（SQL工具）"""
    print("\n=== E2E Test: Order Query (SQL) ===")

    state = AgentState(
        query="查询订单数据",
        plan=[
            {
                "step": 1,
                "tool": "sql_query",
                "api_id": "orders",
                "params": {
                    "query": "SELECT * FROM orders LIMIT 5"
                },
                "description": "查询订单表"
            }
        ],
        current_step=0,
        data_context={},
        messages=[]
    )

    permission = PermissionContext(user_id="1", role="employee")

    # Executor执行
    print("\n[Step 1] Executor execution...")
    state = await executor_node(state, permission)

    data_context = state.get("data_context", {})
    print(f"Data context keys: {list(data_context.keys())}")

    expected_key = "step_0_orders"
    if expected_key in data_context:
        print(f"[PASS] Key format correct: {expected_key}")
        value = data_context[expected_key]
        print(f"Success: {value.get('success')}")
        if value.get("data"):
            print(f"Data rows: {len(value['data']) if isinstance(value['data'], list) else 'N/A'}")
    else:
        print(f"[INFO] Key not found (expected if orders table doesn't exist): {expected_key}")


async def main():
    """运行所有端到端测试"""
    print("=" * 60)
    print("F-11: Executor -> Analyzer 端到端测试")
    print("=" * 60)

    await test_e2e_stock_query()
    await test_e2e_order_query()

    print("\n" + "=" * 60)
    print("测试完成")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
